version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "authservice"
      POSTGRES_USER: "eyndog"
      POSTGRES_PASSWORD: "ppRZP5"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U eyndog -d authservice" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - default
    volumes:
      - data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate

    depends_on:
      postgres:
        condition: service_healthy

    volumes:
      - ./migrations:/migrations

    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://eyndog:ppRZP5@postgres:5432/authservice?sslmode=disable",
        "up"
      ]

  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - migrate
    networks:
      - default
    ports:
      - "7070:8080"

volumes:
  data:
    # migrations:
